<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.19">
  <POU Name="FB_IBuffer" Id="{ac812cbe-1f8b-47d1-861d-77e5638b9fdc}">
    <Declaration><![CDATA[///FUNCTION_BLOCK PUBLIC FB_IBuffer IMPLEMENTS IBuffer
FUNCTION_BLOCK FB_IBuffer EXTENDS FB_CtrlBase IMPLEMENTS IBuffer
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// This is a Dummy-FB, used for the interface (IBuffer) to the buffer-modules]]></ST>
    </Implementation>
    <Property Name="MaxCapacity" Id="{b708dd4b-5b49-4fd6-ab56-49c1ad8d751e}">
      <Declaration><![CDATA[PROPERTY MaxCapacity : DINT
]]></Declaration>
      <Get Name="Get" Id="{7a16a80c-12db-4e9b-a2d5-d16684b8459d}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="NumOfHangers" Id="{64648448-e502-41cf-bc7b-35ef7e411c3a}">
      <Declaration><![CDATA[PROPERTY NumOfHangers : DINT
]]></Declaration>
      <Get Name="Get" Id="{82d4a0d6-e187-412c-801d-93bbbab40c16}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="BufferFull" Id="{4c1362d7-7df8-4e55-b5d5-c9de9c1765e2}">
      <Declaration><![CDATA[PROPERTY BufferFull : BOOL
]]></Declaration>
      <Get Name="Get" Id="{9770096c-d39a-443b-91eb-3e4083830995}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
        <ObjectProperties />
      </Get>
      <ObjectProperties />
    </Property>
    <ObjectProperties>﻿<XmlArchive>
  <Data>
    <o xml:space="preserve" t="POUImageProperty">
      <n n="ImageData" />
      <v n="TransparencyColor">"White"</v>
      <v n="MakeTransparent">false</v>
    </o>
  </Data>
  <TypeList>
    <Type n="Boolean">System.Boolean</Type>
    <Type n="POUImageProperty">{bb741845-1ec5-4be9-bb0d-2cf7058af574}</Type>
    <Type n="String">System.String</Type>
  </TypeList>
</XmlArchive></ObjectProperties>
  </POU>
</TcPlcObject>