<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.19">
  <POU Name="FB_IBuffer" Id="{24f0160e-2b19-49da-9126-0dc45da6966a}">
    <Declaration><![CDATA[///FUNCTION_BLOCK PUBLIC FB_IBuffer IMPLEMENTS IBuffer
FUNCTION_BLOCK FB_IBuffer EXTENDS FB_CtrlBase IMPLEMENTS IBuffer
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// This is a Dummy-FB, used for the interface (IBuffer) to the buffer-modules]]></ST>
    </Implementation>
    <Property Name="MaxCapacity" Id="{54720f97-e6b9-4f2e-9e86-d0a04268d1c7}">
      <Declaration><![CDATA[PROPERTY MaxCapacity : DINT
]]></Declaration>
      <Get Name="Get" Id="{a8f58042-ddb7-4310-b4a0-d305c9cf803a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
        <ObjectProperties />
      </Get>
      <ObjectProperties />
    </Property>
    <Property Name="NumOfHangers" Id="{3ccc6087-6f28-45a1-90be-72725dfde2f0}">
      <Declaration><![CDATA[PROPERTY NumOfHangers : DINT
]]></Declaration>
      <Get Name="Get" Id="{db9fbef5-afd8-4b11-a653-edad81dcf556}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
        <ObjectProperties />
      </Get>
      <ObjectProperties />
    </Property>
    <ObjectProperties />
  </POU>
</TcPlcObject>