<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.19">
  <POU Name="FB_IBuffer" Id="{99c32d67-b773-46cf-8aff-4abd75b8cf23}">
    <Declaration><![CDATA[///FUNCTION_BLOCK PUBLIC FB_IBuffer IMPLEMENTS IBuffer
FUNCTION_BLOCK FB_IBuffer EXTENDS FB_CtrlBase IMPLEMENTS IBuffer
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// This is a Dummy-FB, used for the interface (IBuffer) to the buffer-modules]]></ST>
    </Implementation>
    <Property Name="MaxCapacity" Id="{113bc4e5-dac0-4bc9-8b34-17bee64d79c0}">
      <Declaration><![CDATA[PROPERTY MaxCapacity : DINT
]]></Declaration>
      <Get Name="Get" Id="{d0188fef-bace-4454-bb99-69b5ddf0f13a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="NumOfHangers" Id="{548a5fce-b68a-4a61-956b-6fbf85c1b765}">
      <Declaration><![CDATA[PROPERTY NumOfHangers : DINT
]]></Declaration>
      <Get Name="Get" Id="{0f82b19b-6292-4616-90e5-cbf8c20da661}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <ObjectProperties>﻿<XmlArchive>
  <Data>
    <o xml:space="preserve" t="POUImageProperty">
      <n n="ImageData" />
      <v n="TransparencyColor">"White"</v>
      <v n="MakeTransparent">false</v>
    </o>
  </Data>
  <TypeList>
    <Type n="Boolean">System.Boolean</Type>
    <Type n="POUImageProperty">{bb741845-1ec5-4be9-bb0d-2cf7058af574}</Type>
    <Type n="String">System.String</Type>
  </TypeList>
</XmlArchive></ObjectProperties>
  </POU>
</TcPlcObject>